In [36]:
from pathlib import Path
import pandas as pd

In [37]:
PROCESSED_PATH = Path("../data/processed/hourly_demand_sample.parquet")

df = pd.read_parquet(PROCESSED_PATH)
print(df.shape)
df.head()

(2160, 4)

             datetime         dt  hour  demand
0 2024-03-28 00:00:00 2024-03-28     0     0.3
1 2024-03-28 01:00:00 2024-03-28     1     0.0
2 2024-03-28 02:00:00 2024-03-28     2     0.0
3 2024-03-28 03:00:00 2024-03-28     3     0.2
4 2024-03-28 04:00:00 2024-03-28     4     0.2

## create lag / sliding window

In [38]:
df_rolling = df.copy()

for i in range(1, 25):
    df_rolling[f'lag_{i}'] = df_rolling['demand'].shift(i)

df_rolling = df_rolling.dropna().reset_index(drop=True)

In [39]:
df_rolling.head()

,datetime,dt,hour,demand,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6,...,lag_15,lag_16,lag_17,lag_18,lag_19,lag_20,lag_21,lag_22,lag_23,lag_24
0,2024-03-29 00:00:00,2024-03-29,0,0.6,0.0,0.8,0.5,1.1,3.18,2.70,...,5.4,7.2,4.2,1.7,0.7,0.2,0.2,0.0,0.0,0.3
1,2024-03-29 01:00:00,2024-03-29,1,0.3,0.6,0.0,0.8,0.5,1.10,3.18,...,7.2,5.4,7.2,4.2,1.7,0.7,0.2,0.2,0.0,0.0
2,2024-03-29 02:00:00,2024-03-29,2,0.0,0.3,0.6,0.0,0.8,0.50,1.10,...,4.4,7.2,5.4,7.2,4.2,1.7,0.7,0.2,0.2,0.0
3,2024-03-29 03:00:00,2024-03-29,3,0.4,0.0,0.3,0.6,0.0,0.80,0.50,...,3.7,4.4,7.2,5.4,7.2,4.2,1.7,0.7,0.2,0.2
4,2024-03-29 04:00:00,2024-03-29,4,0.1,0.4,0.0,0.3,0.6,0.00,0.80,...,2.4,3.7,4.4,7.2,5.4,7.2,4.2,1.7,0.7,0.2

In [40]:
df_rolling.columns

Index(['datetime', 'dt', 'hour', 'demand', 'lag_1', 'lag_2', 'lag_3', 'lag_4',
       'lag_5', 'lag_6', 'lag_7', 'lag_8', 'lag_9', 'lag_10', 'lag_11',
       'lag_12', 'lag_13', 'lag_14', 'lag_15', 'lag_16', 'lag_17', 'lag_18',
       'lag_19', 'lag_20', 'lag_21', 'lag_22', 'lag_23', 'lag_24'],
      dtype='str')

In [42]:
PROCESSED_PATH = Path("../data/processed/rolling_sample.parquet")

PROCESSED_PATH.parent.mkdir(parents=True, exist_ok=True)
df_rolling.to_parquet(PROCESSED_PATH, index=False)